### ISSUE TITLE
License

### ISSUE THREAD

**Issue by SivaramSS** [ayaromenok/Android_ImageMagick7#25]
Hi Andrey, 

First of all thank you so much for this awesome port! Great work. It has been of so much help to my project. I wish to make a contribution by writing JNI. License is not specified explicitly anywhere. Am i allowed to fork, modify and redistribute this project?

**Comment by ayaromenok** [comment]
MIT license added as most free from all possible - you allow to work with repo as you like :) 
please note, that code in source directories (/jni/*) use it's own licenses
