### ISSUE TITLE
JMagick evaluation

### ISSUE THREAD

**Issue by ayaromenok** [ayaromenok/Android_ImageMagick7#27]
JMagick https://github.com/techblue/jmagick is a Java interface for ImageMagick 6.5 for PC. it's start to get some fixes for IM7, so maybe it's possible to use with this port for Android/Java

**Comment by MolotovCherry** [comment]
After a lot of work, I've made it so your im7 copy and JMagick work together in Android. I already have it finished and working very well, but there needs to be refinements in the code (I'm working on it)

**Comment by ayaromenok** [comment]
no, thanks ;)
IM7 from this repo works well (except of OpenCL) on every supported architecture, while I decide to not deal with Java since I will not use it anyway ;)

**Comment by MolotovCherry** [comment]
I'm using your copy of IM7, hence the reason I wanted to let you know that I ported JMagic and everything over to work with your copy* (since you posted this issue, I thought for sure you would be happy to hear that, and I pretty much did the work for you ;) ). But ok, nevermind then 

\* Of course I still had to change and edit C files and whatnot to make it more compatible with Android.

**Comment by MolotovCherry** [comment]
For anybody who wants the latest and greatest IM (NOT outdated), with TONS of features (delegates), including optional jmagick support (or you can compile vanilla too), check out my repo.
https://github.com/cherryleafroad/Android-ImageMagick7

P.S. Thanks ayaromenok for helping me figure out the initial port for this.

**Comment by ayaromenok** [comment]
> For anybody who wants the latest and greatest IM (NOT outdated), with TONS of features (delegates), including optional jmagick support (or you can compile vanilla too), check out my repo.
> https://github.com/cherryleafroad/Android-ImageMagick7
> 
> P.S. Thanks ayaromenok for helping me figure out the initial port for this.

Great work! I add a link to you repo in readme.md in root level. 

As I understand, you use a different approach - to port as more features as possible (while my idea was a smaller size and support of all architectures) - so it's good to have both ports!

So, with your help, I close this issue:)

**Comment by MolotovCherry** [comment]
I added a modular system to allow disabling building of features, so size should not be an issue (if the user is willing to build it themselves). Although I could use some work on the architecture front (armeabi7 currently doesn't work)
