### ISSUE TITLE
Warn in big letters on Google Play that this requires the Command Line (e.g., termux)

### ISSUE THREAD

**Issue by jidanni** [ayaromenok/Android_ImageMagick7#30]
You need to make it very clear before the user decides to download the app from Google Play, that It is not imagemagick , but instead it's just it's some kind of test program and it's not going to help you convert your jpgs to anything at all, etc.

**Comment by ayaromenok** [comment]
It is a ImageMagick port to Android (without few file formats, which not widely used) - including libraries(both `MagickCore` and `MagickWand)` and `magick` command-line utility (You can find in release(https://github.com/ayaromenok/Android_ImageMagick7/releases/tag/v0.4.7083.17) in /bin/clang/arm64-v8a/magick for clang/arm64 and for gcc compiler/other architectures too).

And if you like - you can use `magick` to convert you JPEGs to anything (and yes, you need a Android terminal to do it and make sure about adding libraries path to loader - exactly the same way, like on Desktop). 

Repository also include a OpenMP test app - but you don't need to use it.

**Comment by jidanni** [comment]
All I know is what happened to me is probably like the
July 18, 2019 review seen on https://play.google.com/store/apps/details?id=info.yaromenok.IM7Test :
> Terrible, cannot get past running tests. No worth to download.

And all the movie there shows is some tests.

OK if it is working better now, please update the Google Play version.

**Comment by jidanni** [comment]
Well the user expects the app to work something like
https://play.google.com/store/apps/details?id=xeus.timbre

I.e., for users who have no idea of what a command line is,
they can still select what files they want to operate on by clicking on them.

**Comment by ayaromenok** [comment]
App name is **ImgMagick7 Test (Beta)** - which means:
 - this is a **test**
 - this is a **beta**
 - this is no a **ImageMagick** (we don't use Hebrew language style without vowels in English ;))

And main purpose of this test app - to test ability of Image Magick libraries (both Core and Wand) to work in OpenMP mode on different hardware/software.

> July 18, 2019 review seen on https://play.google.com/store/apps/details?id=info.yaromenok.IM7Test :

The answer included in user name of this reviewer - **Infinity Dress Boutique Namibia Windhoek**. It's hard to believe, that C/C++  programmer with Android and image processing experience work in dress boutique somewhere in Namibia ;)

**Comment by jidanni** [comment]
Well my
https://www.facebook.com/jidanni/
says I work at
https://www.facebook.com/yami52422/
so you never know...

OK, so all the app indeed does is just as the
[movie](https://youtu.be/PwSBnWm-JZ8) (which by the way still says "ImageMagic7 for Android",
 as does this [GitHub URL](https://github.com/ayaromenok/Android_ImageMagick7/)) shows.

OK. But all I can say is most users wouldn't expect that test apps would be uploaded to Google Play anyway...

So please don't blame me or that Namibian person for getting confused.

**Comment by ayaromenok** [comment]
@ jidanni  - most of users know, what is ImageMagick, beta, tests, OpenMP etc..  And most of the users don't know about Chinese or dress shops in Namibia.
