### ISSUE TITLE
Add link to Google Play version

### ISSUE THREAD

**Issue by jidanni** [ayaromenok/Android_ImageMagick7#31]
Add link to https://play.google.com/store/apps/details?id=info.yaromenok.IM7Test
on https://github.com/ayaromenok/Android_ImageMagick7 .

**Comment by ayaromenok** [comment]
Link to IM7Test app present in readme.md in the root directory of this repo:
953028b16037d835681b97f895be4ec5efad4930 from yaromenok committed on Nov 6, 2017
