### ISSUE TITLE
implement testApp

### ISSUE THREAD

**Issue by ayaromenok** [ayaromenok/Android_ImageMagick7#5]
- maybe use standard from IM

**Comment by ayaromenok** [comment]
To avoid confusion with  improvements of current project tests implemented in separate repo
https://github.com/ayaromenok/Tests_Android_ImageMagick7

**Comment by kirantpatil** [comment]
This  https://github.com/ayaromenok/Tests_Android_ImageMagick7 repository is not available

**Comment by ayaromenok** [comment]
it was dropped due to technical problems to implement CI test on real hardware, except of armv7/android32

**Comment by ayaromenok** [comment]
https://play.google.com/store/apps/details?id=info.yaromenok.IM7Test

**Comment by ayaromenok** [comment]
New test application added to github and published on google Play:
https://github.com/ayaromenok/IM7Test
https://play.google.com/store/apps/details?id=info.yaromenok.IM7Test
